cmf_routing:
    chain:
        replace_symfony_router: true
        routers_by_id:
            cmf_routing.dynamic_router: 200
            router.default: 100

    dynamic:
        enabled: true
        default_controller: Sfadless\Cmf\Controller\PageController::page
        route_provider_service_id: Sfadless\Cmf\Routing\RouteProvider
        persistence:
            orm:
                enabled: true
                route_class: Sfadless\Cmf\Entity\Content