imports:
    - { resource: cmf/admin.yaml }
    - { resource: cmf/templates.yaml }

parameters:
    locale: 'ru'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\:
        resource: '../src/App/Controller'
        tags: ['controller.service_arguments']

    Sfadless\Cmf\Controller\:
        resource: '../src/Cmf/Controller'
        tags: ['controller.service_arguments']

    Sfadless\Cmf\Security\AdminLoginAuthenticator: ~
    Sfadless\Cmf\Security\UserProvider: ~
    Sfadless\Cmf\DependencyInjection\Compiler\ReplaceServicesPass: ~
    Sfadless\Cmf\Routing\RouteProvider:
        bind:
            $em: '@doctrine.orm.entity_manager'