<?php

namespace App\Admin;

use App\Entity\Content;
use App\Entity\Tag;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Form\Type\AdminType;
use Sonata\AdminBundle\Form\Type\ModelType;

/**
 * ContentAdmin
 *
 * @author Pavel Golikov <pgolikov327@gmail.com>
 */
class ContentAdmin extends AbstractAdmin
{
    public function configureFormFields(FormMapper $form)
    {
        $form
            ->add('content', CKEditorType::class)
            ->add('route', AdminType::class, [
                'label' => 'Настройки Url',
            ])
            ->add('tags',  ModelType::class, [
                'required' => false,
                'multiple' => true,
                'class' => Tag::class,
                'property' => 'name',
                'label' => 'Теги',
                'btn_list' => "Просмотр",
                'btn_add' => "Добавить",
                'btn_delete' => true
            ])
        ;
    }

    /**
     * @param $object Content
     */
    public function preUpdate($object)
    {
        $route = $object->getRoute();

        if (! $route->getName()) {
            $route->setName($route->getStaticPrefix());
        }
    }

    public function prePersist($object)
    {
        parent::prePersist($object); // TODO: Change the autogenerated stub
    }

    public function configureListFields(ListMapper $list)
    {
        $list->addIdentifier('id');
    }
}